### ISSUE TITLE
add server's role settings

### ISSUE THREAD

**Issue by k-ta-yamada** [k-ta-yamada/systemd_service_check#20]
### systemd_service_check.sample.yml

```yaml
servers:
  - env:      dev
    role:     ap # <- add this key
    ip:       192.168.1.101
    user:     root
    password: vagrant
    services: *default_services
  - env:      dev
    role:     db # <- add this key
    ip:       192.168.1.101
    user:     root
    password: vagrant
    services: *default_services
  - env:      stg
    role:     ap # <- add this key
    ip:       192.168.1.101
    user:     root
    password: vagrant
    services: *default_services
```

### Usage image

```
# All for `dev` environment
ssc chceck dev

# Only for `ap` role of `dev` environment
ssc check dev --role ap

# All for `ap` roles
ssc check all --role ap

# Only for `ap` role of `dev` and `stg` environments
ssc check dev stg --role ap

```
